# Generated by Django 5.0.2 on 2024-02-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='animais_perdidos/%Y/%m/%d/')),
            ],
        ),
    ]
