# Generated by Django 5.0.2 on 2024-02-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalperdido',
            name='descricao',
        ),
        migrations.AddField(
            model_name='animalperdido',
            name='raca',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
