# Generated by Django 5.0.2 on 2024-03-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_api', '0002_remove_animalperdido_descricao_animalperdido_raca'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalperdido',
            name='endereco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='animalperdido',
            name='raca',
            field=models.CharField(default='', max_length=100),
        ),
    ]
